FROM mysql:8.0
LABEL authors="adkham"

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=urlshrtenerdb
ENV MYSQL_USER=appuser
ENV MYSQL_PASSWORD=apppass123
VOLUME mysql_data:/var/lib/mysql
EXPOSE 3306
