apiVersion: v1
data:
  database: dXJsc2hydGVuZXJkYg==
  password: YXBwcGFzczEyMw==
  root-password: cm9vdHBhc3MxMjM=
  username: YXBwdXNlcg==
kind: Secret
metadata:
  creationTimestamp: "2026-08-28T14:39:46Z"
  name: mysql-secret
  namespace: default
  resourceVersion: "4583814"
  uid: 02418fc4-b34b-479e-bb1e-f195373c3509
type: Opaque
